mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mythril/interfaces/cli.py", line 975, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/usr/local/lib/python3.10/site-packages/mythril/interfaces/cli.py", line 726, in load_code
    address, _ = disassembler.load_from_solidity(
  File "/usr/local/lib/python3.10/site-packages/mythril/mythril/mythril_disassembler.py", line 277, in load_from_solidity
    solc_binary, self.solc_version = util.extract_binary(file)
  File "/usr/local/lib/python3.10/site-packages/mythril/ethereum/util.py", line 222, in extract_binary
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp//home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/10/contracts/contracts/hypervisor/PowerSwitchFactory.sol'

