'solc --version' running
'solc /home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc' running
Compilation warnings/errors on /home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:
[91m/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:4:1: Error: Source "@timeswap-labs/timeswap-v1-core/contracts/interfaces/IPair.sol" not found: File not found.[0m
import {IPair} from '@timeswap-labs/timeswap-v1-core/contracts/interfaces/IPair.sol';
^-----------------------------------------------------------------------------------^
[91m/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:5:1: Error: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.[0m
import {IERC20} from '@openzeppelin/contracts/token/ERC20/IERC20.sol';
^--------------------------------------------------------------------^
[91m/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:6:1: Error: Source "/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/libraries/SafeTransfer.sol" not found: File outside of allowed directories.[0m
import {SafeTransfer} from '../libraries/SafeTransfer.sol';
^---------------------------------------------------------^

Traceback (most recent call last):
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 582, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 207, in __init__
    self._compile(**kwargs)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 629, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 151, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 280, in _get_targets_json
    return _run_solc(
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 586, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation /home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:4:1: Error: Source "@timeswap-labs/timeswap-v1-core/contracts/interfaces/IPair.sol" not found: File not found.
import {IPair} from '@timeswap-labs/timeswap-v1-core/contracts/interfaces/IPair.sol';
^-----------------------------------------------------------------------------------^
/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:5:1: Error: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
import {IERC20} from '@openzeppelin/contracts/token/ERC20/IERC20.sol';
^--------------------------------------------------------------------^
/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:6:1: Error: Source "/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/libraries/SafeTransfer.sol" not found: File outside of allowed directories.
import {SafeTransfer} from '../libraries/SafeTransfer.sol';
^---------------------------------------------------------^

None
Error in /home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol
Traceback (most recent call last):
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 582, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 207, in __init__
    self._compile(**kwargs)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 629, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 151, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 280, in _get_targets_json
    return _run_solc(
  File "/home/sallyjunsongwang/.local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 586, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation /home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:4:1: Error: Source "@timeswap-labs/timeswap-v1-core/contracts/interfaces/IPair.sol" not found: File not found.
import {IPair} from '@timeswap-labs/timeswap-v1-core/contracts/interfaces/IPair.sol';
^-----------------------------------------------------------------------------------^
/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:5:1: Error: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
import {IERC20} from '@openzeppelin/contracts/token/ERC20/IERC20.sol';
^--------------------------------------------------------------------^
/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/test/SafeTransferCallee.sol:6:1: Error: Source "/home/sallyjunsongwang/SmartInv/tests/refined_analysis/additional_audited_bugs/74/Timeswap/Timeswap-V1-Convenience/contracts/libraries/SafeTransfer.sol" not found: File outside of allowed directories.
import {SafeTransfer} from '../libraries/SafeTransfer.sol';
^---------------------------------------------------------^


